<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Submit</name>
   <tag></tag>
   <elementGuidId>c1ae07e8-a43e-402f-8ffa-eeaa08a9e8c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@class='app-button upload-button action-color-bg primary-color fw500']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.app-button.upload-button.action-color-bg.primary-color.fw500</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8c65336c-d9b5-4728-bb71-dbf100810b24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>app-button upload-button action-color-bg primary-color fw500</value>
      <webElementGuid>c7a71a01-3627-4002-9ac3-032c0e0bc39d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>99134bd8-29dd-42bf-8dbd-99e8fb79ad17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>b1162577-5381-41e8-9a49-a83ca550cce5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;full-width dashboard-wrapper full-vh&quot;]/div[@class=&quot;p-relative fade-in dashboard-layout full-height&quot;]/div[@class=&quot;fade-in full-width content-wrapper&quot;]/div[@class=&quot;reg-container margin-auto&quot;]/div[@class=&quot;stepper-layout d-flex flex-vertical&quot;]/div[@class=&quot;form-content-stepper&quot;]/div[@class=&quot;reg-form-margin-top reg-stepper-padding border-radius5  app-padding-starter-tb form-padding-lr primary-bg-color d-flex flex-vertical align-center&quot;]/div[@class=&quot;d-flex flex-vertical full-width full-height&quot;]/div[@class=&quot;flex-one&quot;]/form[@class=&quot;account-detail&quot;]/div[@class=&quot;p-fixed full-height full-width popup&quot;]/div[@class=&quot;d-flex j-center&quot;]/div[@class=&quot;popup-content p-relative&quot;]/div[@class=&quot;p-relative&quot;]/div[@class=&quot;d-flex justify-end full-width&quot;]/button[@class=&quot;app-button upload-button action-color-bg primary-color fw500&quot;]</value>
      <webElementGuid>8b0a431c-ae9b-402e-8573-160c10e42547</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[3]</value>
      <webElementGuid>929bba01-ec01-485d-8931-450556132682</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/div[2]/div/div[2]/div/div/div/form/div[12]/div/div/div[5]/div[2]/button</value>
      <webElementGuid>b23b3102-bab3-4597-b9c9-8bfc4a7d8f64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BVN'])[1]/following::button[1]</value>
      <webElementGuid>6b298406-a0d9-4df8-b3a7-5dfd233653e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Compliance'])[2]/following::button[8]</value>
      <webElementGuid>f93e957b-db3d-491a-8ed7-c5a63287f518</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Support'])[1]/preceding::button[1]</value>
      <webElementGuid>f6963906-bbfa-4747-bed9-fca326eedfb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::button[2]</value>
      <webElementGuid>ecac367a-2837-436a-8ee9-76b1f0061221</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Submit']/parent::*</value>
      <webElementGuid>5147992a-152f-4eb3-b16a-3ed7e2a8707c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/button</value>
      <webElementGuid>f4d541f2-2e27-4e06-876b-740b4fba819c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Submit' or . = 'Submit')]</value>
      <webElementGuid>eca0c6f5-a4db-41e2-878b-6c4800fbad2c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
