<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_BVN OTP 5</name>
   <tag></tag>
   <elementGuidId>f7db1d65-3bf5-4edd-99ea-232595229667</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='06dc8b82-23f1-4151-81ab-cc7575270da8-4']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#06dc8b82-23f1-4151-81ab-cc7575270da8-4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>818c690f-bc1c-4c11-aaa0-26b4f589131d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>06dc8b82-23f1-4151-81ab-cc7575270da8-4</value>
      <webElementGuid>c75cde1a-88aa-4514-b50f-a40684b444ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>ab5fadde-4e65-4102-b937-8cb185d61a2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>ba14d7a5-3423-44a0-bfe7-5c5191858c57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6ea3475f-cdbc-4e0e-b7c9-b4ac00814199</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>020056e4-2a95-4c4d-8d4a-0a94fd3debaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>f0953767-fdac-46a0-abd2-a792428b55d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>chrome-off</value>
      <webElementGuid>87d214d5-7073-4b66-8459-9a9c1aa0c47b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-valid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>49e4f848-53bd-4bfb-a6e9-2c20dc375467</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>/^\d+$/</value>
      <webElementGuid>bafa215f-4f32-47a4-be29-fb7c37d425fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;06dc8b82-23f1-4151-81ab-cc7575270da8-4&quot;)</value>
      <webElementGuid>e6b6465d-233f-4aa3-9089-1c0e586a3193</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='06dc8b82-23f1-4151-81ab-cc7575270da8-4']</value>
      <webElementGuid>29eb9225-7504-4150-b3e5-e944ae7c5bbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/div[2]/div/div[2]/div/div/div/form/div[12]/div/div/div[4]/div/input[5]</value>
      <webElementGuid>32e61ff4-e1f5-427d-a065-b38f7c2e1426</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[5]</value>
      <webElementGuid>3a5a5354-c6ad-435d-8d81-ec42c7d19716</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '06dc8b82-23f1-4151-81ab-cc7575270da8-4' and @type = 'password']</value>
      <webElementGuid>65422784-ba18-4a31-9822-24fd311d8539</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
