<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_BVN OTP 1</name>
   <tag></tag>
   <elementGuidId>a307ff87-c5f2-4dcc-a5c9-c04199ca1b10</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='06dc8b82-23f1-4151-81ab-cc7575270da8-0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#06dc8b82-23f1-4151-81ab-cc7575270da8-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>37d8b452-b97d-4da4-a2ab-18429bcf6d62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>06dc8b82-23f1-4151-81ab-cc7575270da8-0</value>
      <webElementGuid>74ad1468-1784-450f-b320-248996fef7ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8d47fbc0-1b0f-4bd5-93ea-ca3faa7e286c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>85e6c7bf-085a-4ce2-8a04-6d5c8c227df5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>593c0898-49b6-4731-b853-dc5ffa4c6409</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>03d3a071-9b36-40f3-816b-cc1c6486a2b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>a2cb9f3f-de3e-4cda-a2c4-522770ab5fed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>chrome-off</value>
      <webElementGuid>ecc18637-95ef-49c2-a6b0-69e32c35a1f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-valid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>719f430f-f0f6-4a68-9753-2a81a154e087</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>/^\d+$/</value>
      <webElementGuid>ba05e7da-4244-4cd9-b5d0-9308b71f951d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;06dc8b82-23f1-4151-81ab-cc7575270da8-0&quot;)</value>
      <webElementGuid>4da2e8c0-06b8-4ec9-b33f-93176fd994b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='06dc8b82-23f1-4151-81ab-cc7575270da8-0']</value>
      <webElementGuid>c453fd70-582b-4acd-b3e6-7723420f8818</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/div[2]/div/div[2]/div/div/div/form/div[12]/div/div/div[4]/div/input</value>
      <webElementGuid>cb6f25df-47fa-4ad3-992a-bb0073c9d544</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>5fd849a2-bf7b-4f40-9fac-d53085e2c7f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '06dc8b82-23f1-4151-81ab-cc7575270da8-0' and @type = 'password']</value>
      <webElementGuid>f0641cfc-766c-4793-9a27-87682f98d1c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
