<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_pin 3</name>
   <tag></tag>
   <elementGuidId>ff1a061f-a650-4c8a-89bb-dc593e7307ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#05155d04-8d40-4af3-af76-6cf53153d521-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='password' and @data-id='2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9a1570ed-2870-44b6-880a-ce483dafe8cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>05155d04-8d40-4af3-af76-6cf53153d521-2</value>
      <webElementGuid>6bc5fbc3-f3b0-4691-8537-20e31c4338d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>153f22f3-35fd-4adf-90e9-e4aba44af859</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>82f2a019-a742-4efc-948f-8e23b7043a2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6bcfeca5-a68f-42a3-8b3f-e51924479a97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>a6841dc6-7838-427d-b226-366190492735</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>e079886f-c91f-412a-b47b-83aa29ae5d5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>chrome-off</value>
      <webElementGuid>3eb63748-2ec5-4332-9af7-a2e1f9caa721</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-valid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a0c3c111-7fdf-4ebe-8c20-34bf16aafc65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>/^\d+$/</value>
      <webElementGuid>1523aeb2-0764-4bfe-bd6c-b434a51ce94e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;05155d04-8d40-4af3-af76-6cf53153d521-2&quot;)</value>
      <webElementGuid>50a538f5-fa8b-43a2-9a78-4488449fc0c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='05155d04-8d40-4af3-af76-6cf53153d521-2']</value>
      <webElementGuid>30409230-eebb-4221-a28a-7e845ee965fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/div[3]/div/div/div[4]/div/input[3]</value>
      <webElementGuid>19239bd5-b9ea-40c0-bdb1-6185e863be45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[3]</value>
      <webElementGuid>554e338c-2ad9-46da-84ab-7147ee0c4a61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '05155d04-8d40-4af3-af76-6cf53153d521-2' and @type = 'password']</value>
      <webElementGuid>df1724dd-e531-42fb-a9b1-4421a49f8274</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
