<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Send whatsapp message</name>
   <tag></tag>
   <elementGuidId>0f9c092d-c288-4b0a-ac27-13aee5d90ce3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.text-color.opacity-5.anchor-tag</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@class='text-color opacity-5 anchor-tag']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f0ee0ec0-59cc-4255-818d-4380055d9720</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>1d54af98-4002-4812-8c43-c774cfe5b182</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>noreferrer</value>
      <webElementGuid>50a1a218-3eb2-45ea-9dd7-444680b1c8fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-color opacity-5 anchor-tag</value>
      <webElementGuid>3d5d9388-b987-4ff7-b486-5431d2ed062b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://wa.me/2348028108892</value>
      <webElementGuid>0adab4ac-d014-4e96-857b-67a2fc922476</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>https://wa.me/2348028108892</value>
      <webElementGuid>438c671f-4ff7-475e-8e4f-81985dc5c988</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-tabs-0-panel-Support&quot;)/div[@class=&quot;full-height flex-vertical full-width d-flex align-center j-center&quot;]/div[@class=&quot;d-grid card-grid&quot;]/div[@class=&quot;p-relative lo&quot;]/div[@class=&quot;d-flex flex-vertical back-card c-pointer  align-center&quot;]/div[@class=&quot;d-flex flex-vertical&quot;]/div[@class=&quot;d-flex align-center&quot;]/p[@class=&quot;no-margin link-l text-center fw400 font-size-15&quot;]/a[@class=&quot;text-color opacity-5 anchor-tag&quot;]</value>
      <webElementGuid>10123113-d215-4ace-b69b-cbcab442de30</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-tabs-0-panel-Support']/div/div[2]/div[2]/div[2]/div[4]/div[3]/p/a</value>
      <webElementGuid>0e14e593-eafd-4234-98e1-f6d10479b806</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'https://wa.me/2348028108892')]</value>
      <webElementGuid>682bc30a-832c-4229-86e6-1c390d6c31dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='support@vpay.africa'])[1]/following::a[1]</value>
      <webElementGuid>e6622ee7-5237-441c-8816-c53404509d32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Send Us A Message'])[1]/following::a[2]</value>
      <webElementGuid>42abb2a9-00a4-4f8c-a824-3fbb3b9a15a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='https://t.me/joinchat/nqPoWpDU5wk4MjE8'])[1]/preceding::a[1]</value>
      <webElementGuid>4ecab447-cd1a-46bb-93dd-70424b1cad03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Suggest An Improvement'])[1]/preceding::a[2]</value>
      <webElementGuid>cb31a4ff-90d4-4971-8a3a-4ce897c6d641</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='https://wa.me/2348028108892']/parent::*</value>
      <webElementGuid>f8b8f08b-f4fb-4085-8121-c16c199ed95f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://wa.me/2348028108892')]</value>
      <webElementGuid>8c993f2b-dade-43fa-9518-b05cf940f304</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/p/a</value>
      <webElementGuid>d1a7e31c-e80c-495b-932b-efff5d6a2d86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://wa.me/2348028108892' and (text() = 'https://wa.me/2348028108892' or . = 'https://wa.me/2348028108892')]</value>
      <webElementGuid>f91ad161-fca9-443e-8a61-d898e6204cbe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
