<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>close QR code view</name>
   <tag></tag>
   <elementGuidId>250430e1-c698-4979-8770-1a60d29b384a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.unstyle-button.c-pointer.rounded-widget.text-center.text-white.container-size-small.d-flex.align-center.j-center</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@class='unstyle-button c-pointer rounded-widget text-center text-white container-size-small d-flex align-center j-center']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7ad5b1a3-efb9-47cf-a649-661374aae20d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ee3e5e59-eba0-44fc-bac6-b91083c2bb2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>unstyle-button c-pointer rounded-widget text-center text-white container-size-small d-flex align-center j-center</value>
      <webElementGuid>1a684991-015f-41eb-ae54-2aa3b32ced98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;full-width dashboard-wrapper full-vh&quot;]/div[@class=&quot;p-relative fade-in dashboard-layout full-height&quot;]/div[@class=&quot;d-flex flex-vertical fade-in full-width content-wrapper&quot;]/div[@class=&quot;p-fixed full-height full-width popup&quot;]/div[@class=&quot;d-flex j-center&quot;]/div[@class=&quot;popup-content p-relative&quot;]/div[@class=&quot;title-area d-flex align-center&quot;]/button[@class=&quot;unstyle-button c-pointer rounded-widget text-center text-white container-size-small d-flex align-center j-center&quot;]</value>
      <webElementGuid>9cfbebe7-6848-497f-8d82-2054e0cbaf55</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>e4938acd-3efc-4f5d-b239-ed2ad352a9f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/div[3]/div/div/div/button</value>
      <webElementGuid>a47e6489-0784-4a2e-9d4b-bc15e602dd61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='See More'])[2]/following::button[1]</value>
      <webElementGuid>05b3368a-c30b-44e0-a214-9741542503c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apr'])[1]/following::button[6]</value>
      <webElementGuid>4fbb461c-fc6d-42de-a911-6bbb32399354</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='candice@givmail.com'])[1]/preceding::button[1]</value>
      <webElementGuid>fb29ab0e-dbd1-4f7e-8c5c-c38fa8e1c9b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account Details'])[1]/preceding::button[1]</value>
      <webElementGuid>8ec633c5-e14c-43e3-af97-02d364625f71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/button</value>
      <webElementGuid>734b9f36-850a-4b32-8524-18dafd0173b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button']</value>
      <webElementGuid>ec365e99-9bc2-4977-9074-ef91eee42d56</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
