<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Fall over Hover on Send Admin message</name>
   <tag></tag>
   <elementGuidId>dcc0e76c-e46e-4c7b-8428-185ace5e60ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-tabs-0-panel-Support']/div/div[2]/div[2]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b0680ab2-7d31-4062-b155-8a878ab672db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-flex flex-vertical back-card c-pointer  align-center</value>
      <webElementGuid>62e9e29a-8591-480c-8ae2-831a19dd91fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Send Us A Messagesupport@vpay.africahttps://wa.me/2348028108892https://t.me/joinchat/nqPoWpDU5wk4MjE8</value>
      <webElementGuid>17f5b4a8-6b3e-44be-b40f-a00fd6c5ac1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-tabs-0-panel-Support&quot;)/div[@class=&quot;full-height flex-vertical full-width d-flex align-center j-center&quot;]/div[@class=&quot;d-grid card-grid&quot;]/div[@class=&quot;p-relative lo&quot;]/div[@class=&quot;d-flex flex-vertical back-card c-pointer  align-center&quot;]</value>
      <webElementGuid>7c6565ce-a997-46f6-88ab-a87dd745aa74</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-tabs-0-panel-Support']/div/div[2]/div[2]/div[2]</value>
      <webElementGuid>4c90114d-5421-4ae9-810b-6ab6139380fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chat Admin'])[1]/following::div[1]</value>
      <webElementGuid>a7f14424-d376-446d-a9b2-00617743a08d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get In touch'])[1]/following::div[3]</value>
      <webElementGuid>1336b812-8b59-420e-90b1-3a399ca6ad2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]</value>
      <webElementGuid>0e0253fc-ed75-412f-b0d2-af4848ae4978</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Send Us A Messagesupport@vpay.africahttps://wa.me/2348028108892https://t.me/joinchat/nqPoWpDU5wk4MjE8' or . = 'Send Us A Messagesupport@vpay.africahttps://wa.me/2348028108892https://t.me/joinchat/nqPoWpDU5wk4MjE8')]</value>
      <webElementGuid>c5fc8005-038c-45c8-9101-ee61635a035a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
