<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>copy icon for Ussd code</name>
   <tag></tag>
   <elementGuidId>dc224a47-a2a8-4c74-a4d1-612b0dc49590</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.c-pointer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='d-flex align-baseline full-width']//img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>0a453857-bf7a-4722-9793-0a6fb2f6d0ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c-pointer</value>
      <webElementGuid>17a7be18-5802-4b30-96e8-c9d5d9f37481</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/static/media/clip.1fd151f6.svg</value>
      <webElementGuid>51446fdc-1d9a-4bd6-bd32-211b75b78b78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;full-width dashboard-wrapper full-vh&quot;]/div[@class=&quot;p-relative fade-in dashboard-layout full-height&quot;]/div[@class=&quot;d-flex flex-vertical fade-in full-width content-wrapper&quot;]/div[@class=&quot;p-fixed full-height full-width popup&quot;]/div[@class=&quot;d-flex j-center&quot;]/div[@class=&quot;popup-content p-relative&quot;]/div[@class=&quot;d-flex flex-vertical align-center&quot;]/div[@class=&quot;d-flex align-baseline full-width&quot;]/img[@class=&quot;c-pointer&quot;]</value>
      <webElementGuid>66241ca2-4148-4679-9b92-ca7bf45d7bc3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/div[3]/div/div/div[2]/div[10]/img</value>
      <webElementGuid>0a77fb2b-b7c1-4fdc-9280-a0922e674db3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/img</value>
      <webElementGuid>68830831-752b-44d9-85f9-bba7d39465e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/static/media/clip.1fd151f6.svg']</value>
      <webElementGuid>936ed8cd-e665-4e57-99b4-5528a2738857</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
