<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(id(, , chat-widget, , ))_chat-widget</name>
   <tag></tag>
   <elementGuidId>1d081985-42f8-4fb8-9e26-8d2261115230</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#chat-widget</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='chat-widget']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>a5d767e5-213f-477c-8c1b-09f55da2f850</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>autoplay; microphone *; camera *; display-capture *; picture-in-picture *; fullscreen *;</value>
      <webElementGuid>e196e8a5-e123-4672-969d-e6ae2b8da783</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://secure.livechatinc.com/customer/action/open_chat?license_id=12924519&amp;group=0&amp;embedded=1&amp;widget_version=3&amp;unique_groups=0</value>
      <webElementGuid>7e710866-e543-49e3-b8e9-bb2b0241ec2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a4d86ebf-5a59-4e30-a210-ba527cd26ff8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>chat-widget</value>
      <webElementGuid>3d49b48e-1125-4284-bf25-9ce4ed229e27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>chat-widget</value>
      <webElementGuid>2aab8132-4563-4b53-b185-8202504b2a37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>LiveChat chat widget</value>
      <webElementGuid>7ae9a724-a6d0-4652-b93c-7b8a3aa35f42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>a3ef9fe1-b176-40c3-bbbd-d66722c29419</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chat-widget&quot;)</value>
      <webElementGuid>e795a0dc-b8f0-4f68-b5d1-25a0956abc2e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='chat-widget']</value>
      <webElementGuid>5e0cecca-9fc6-4ec6-bf6f-5ae0e124dc19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chat-widget-container']/iframe</value>
      <webElementGuid>c28042ac-0598-4e06-8f31-db8725fe900f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>8a0f6619-13b6-4d26-bfcd-52f597dfabf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://secure.livechatinc.com/customer/action/open_chat?license_id=12924519&amp;group=0&amp;embedded=1&amp;widget_version=3&amp;unique_groups=0' and @id = 'chat-widget' and @name = 'chat-widget' and @title = 'LiveChat chat widget']</value>
      <webElementGuid>9d3204ee-d612-4cf8-8f16-9ace0213f46f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
