<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(id(, , chat-widget, , ))_chat-widget</name>
   <tag></tag>
   <elementGuidId>1a17ea85-1a11-408b-b32c-be197dfb9170</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='chat-widget']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#chat-widget</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>54019299-59e2-41d8-8789-f3f3f98fc963</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>autoplay; microphone *; camera *; display-capture *; picture-in-picture *; fullscreen *;</value>
      <webElementGuid>233e4fe4-96c2-4047-bb28-cd7c0e1ee076</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://secure.livechatinc.com/customer/action/open_chat?license_id=12924519&amp;group=0&amp;embedded=1&amp;widget_version=3&amp;unique_groups=0</value>
      <webElementGuid>85a87161-a4c5-4b2b-8a49-1ba58e38d335</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3d1b7fed-2216-435c-88b2-843e9a23217d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>chat-widget</value>
      <webElementGuid>a3f93036-af7f-40d9-b8ca-6e04d4b6e210</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>chat-widget</value>
      <webElementGuid>61f106d2-228f-44a4-846e-e9769b1fe485</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>LiveChat chat widget</value>
      <webElementGuid>4f87d07f-e835-48c1-986e-2bb236fe8423</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>66f315bb-23f8-4082-a7c2-dc8bbc4b63c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cd_frame_id_</name>
      <type>Main</type>
      <value>74eedc793673c13677413d4d129188fb</value>
      <webElementGuid>2d9a2320-d278-4459-983e-22ae62c06656</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chat-widget&quot;)</value>
      <webElementGuid>011d5dc8-085b-4ece-9ddc-bc96a5a0f809</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='chat-widget']</value>
      <webElementGuid>08378570-6268-4d90-ab04-fea81a97d078</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chat-widget-container']/iframe</value>
      <webElementGuid>2a817737-297a-4468-86cf-15b03e66101d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>eb5a35d4-de7a-4bbe-9b0b-e1542e2432d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://secure.livechatinc.com/customer/action/open_chat?license_id=12924519&amp;group=0&amp;embedded=1&amp;widget_version=3&amp;unique_groups=0' and @id = 'chat-widget' and @name = 'chat-widget' and @title = 'LiveChat chat widget']</value>
      <webElementGuid>93bdf5e3-ba10-4fbb-b723-9746aad18ac3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
