<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_close tour</name>
   <tag></tag>
   <elementGuidId>f39a3daf-1153-49a6-a689-2c044b031a2e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.c-pointer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div/div/div/div[3]/div[2]/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c46c1272-ff34-4e62-8b80-c4dd5380f3b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c-pointer</value>
      <webElementGuid>fd7face1-4470-4549-8c22-7150c56d395b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/static/media/iconClose.71c67d5c.svg</value>
      <webElementGuid>02eae707-f7b8-4d66-93ba-f8077dbce3c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>close action</value>
      <webElementGuid>9f4437b6-5e56-405e-98f9-ad26cf7bd59f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;tour-active full-width dashboard-wrapper full-vh&quot;]/div[@class=&quot;p-relative fade-in dashboard-layout full-height&quot;]/div[@class=&quot;d-flex dashboard-header full-width&quot;]/div[1]/div[@class=&quot;d-flex no-mobile j-center align-center p-relative&quot;]/div[@class=&quot;p-relative z-index200 border-radius15&quot;]/div[@class=&quot;tour-triangle-right tour-content p-fixed&quot;]/div[@class=&quot;d-flex align-center j-space-between&quot;]/img[@class=&quot;c-pointer&quot;]</value>
      <webElementGuid>b186f879-2d7c-4167-8e82-8134b9f743a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div/div[3]/div[2]/div/img</value>
      <webElementGuid>3ddc8343-8c9c-4a17-9915-2b0afab9479e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='close action']</value>
      <webElementGuid>7977dacc-b86c-4bb4-84f2-f45bfd853bc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/img</value>
      <webElementGuid>b3be9f3c-0d00-4520-9efd-a57a771562a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/static/media/iconClose.71c67d5c.svg' and @alt = 'close action']</value>
      <webElementGuid>2fa447b8-32bc-4eae-9c3b-4c5bd6b84469</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
