<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_pin 3</name>
   <tag></tag>
   <elementGuidId>e5ff91d9-6e98-4db2-b98d-62facd1bcbb1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#05155d04-8d40-4af3-af76-6cf53153d521-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='password' and @data-id='2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>112f7eae-edbf-48ba-bdd7-bf8d1346d856</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>05155d04-8d40-4af3-af76-6cf53153d521-2</value>
      <webElementGuid>348af362-0967-47f2-8cfc-41acf7dc41b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>c9a63d64-4dc7-4ad4-811a-595370e3a523</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>d37820e2-c0ad-4779-a66f-5068d8defbc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d282cd71-75ff-49fe-9b2e-675b44b01d5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>462ce16a-a00e-4f1d-84af-c1728522ccb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>2045e9ac-659f-46f3-86aa-65aa187a8d8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>chrome-off</value>
      <webElementGuid>0e10b700-1024-4262-8dc6-e9299b2093d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-valid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5029d561-8fee-4e39-a934-6172da4f69dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>/^\d+$/</value>
      <webElementGuid>e8bc8848-87a6-4e5c-85b2-bb87ee5c7e61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;05155d04-8d40-4af3-af76-6cf53153d521-2&quot;)</value>
      <webElementGuid>c8f1980e-d032-473b-803e-c00949040d78</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='05155d04-8d40-4af3-af76-6cf53153d521-2']</value>
      <webElementGuid>ff5b34e7-f5bd-4f5b-abbc-46288443b08d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/div[3]/div/div/div[4]/div/input[3]</value>
      <webElementGuid>efc9b6c1-832e-4fe8-961d-d7c213599d47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[3]</value>
      <webElementGuid>21ebd4df-692d-4066-8364-88c65e846cf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '05155d04-8d40-4af3-af76-6cf53153d521-2' and @type = 'password']</value>
      <webElementGuid>c91b362d-6bb1-454e-9dd5-4d826e5f4831</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
