<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_pin 1</name>
   <tag></tag>
   <elementGuidId>6bf92374-8e99-4712-9014-7fe2202a51ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#05155d04-8d40-4af3-af76-6cf53153d521-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='password' and @data-id='0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>428b3eae-fc2d-47e8-9bef-252131f61e5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>05155d04-8d40-4af3-af76-6cf53153d521-0</value>
      <webElementGuid>2d875c9e-a89d-4491-b779-ff1769859ae5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3748324f-853e-487a-a232-47be4899d96d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>44c649ff-2fab-45f6-9893-ccf3582a8c6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>fcec7547-2255-4966-bbec-b7fed45ada13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>dbb30547-ddfb-4abf-b77e-8233f6008891</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>4d5afb07-f1ce-4ff5-9407-2d7f7c94e088</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>chrome-off</value>
      <webElementGuid>40230c77-2092-4f83-a77a-c78a2ecdc23a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-valid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ee7c885f-a6e1-4430-a3da-0017728caaf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>/^\d+$/</value>
      <webElementGuid>b055178a-36b7-4bbc-a81b-c646201aac7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;05155d04-8d40-4af3-af76-6cf53153d521-0&quot;)</value>
      <webElementGuid>968cf5e8-094c-47c8-9162-b9cf389074e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='05155d04-8d40-4af3-af76-6cf53153d521-0']</value>
      <webElementGuid>ad270646-e116-43ce-af6e-5a10816e0051</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/div[3]/div/div/div[4]/div/input</value>
      <webElementGuid>8e9ed8f8-dc08-4bc2-bd43-ef058da51ab4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>27bdfee9-6b62-44da-b4b5-236f1ef48462</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '05155d04-8d40-4af3-af76-6cf53153d521-0' and @type = 'password']</value>
      <webElementGuid>dd568fe8-02e5-456b-8af4-27600506d88b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
