<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Send telegram message</name>
   <tag></tag>
   <elementGuidId>88196c21-57d5-4f67-91b9-912932a6872c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@class='text-color anchor-tag opacity-5']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>62748083-3810-4624-a4e5-0fa3edebefd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>9e4e2af5-6a86-4c7b-85a5-dde0fbb7cbdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>noreferrer</value>
      <webElementGuid>16644787-39a2-4424-9b82-bcf4b9014a98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-color anchor-tag opacity-5</value>
      <webElementGuid>515cd460-d244-42e9-aa92-364cc311447d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://t.me/joinchat/nqPoWpDU5wk4MjE8</value>
      <webElementGuid>5ae07762-51da-40d5-a490-9a508f4d3312</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>https://t.me/joinchat/nqPoWpDU5wk4MjE8</value>
      <webElementGuid>0a598836-ba44-4a91-ab3d-feef9e90a2f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-tabs-0-panel-Support&quot;)/div[@class=&quot;full-height flex-vertical full-width d-flex align-center j-center&quot;]/div[@class=&quot;d-grid card-grid&quot;]/div[@class=&quot;p-relative lo&quot;]/div[@class=&quot;d-flex flex-vertical back-card c-pointer  align-center&quot;]/div[@class=&quot;d-flex flex-vertical&quot;]/div[@class=&quot;d-flex align-center&quot;]/p[@class=&quot;no-margin link-l text-center fw400 font-size-15&quot;]/a[@class=&quot;text-color anchor-tag opacity-5&quot;]</value>
      <webElementGuid>626fa14a-76ec-4999-8703-18777409447b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-tabs-0-panel-Support']/div/div[2]/div[2]/div[2]/div[4]/div[5]/p/a</value>
      <webElementGuid>cc45bc71-64a6-4ac8-bae9-78eab1435aa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'https://t.me/joinchat/nqPoWpDU5wk4MjE8')]</value>
      <webElementGuid>c18383ea-048b-40b6-98c4-90f129e05004</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='https://wa.me/2348028108892'])[1]/following::a[1]</value>
      <webElementGuid>e3105f46-61cb-4490-b235-303ba2af20a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='support@vpay.africa'])[1]/following::a[2]</value>
      <webElementGuid>4b17766e-684b-452e-b92a-2d98970ba8a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Suggest An Improvement'])[1]/preceding::a[1]</value>
      <webElementGuid>b6c87f2e-2430-481d-9368-4a6806211f27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Make A Suggestion'])[1]/preceding::a[1]</value>
      <webElementGuid>f1907d0b-ba59-447b-9a13-444b3a41488f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='https://t.me/joinchat/nqPoWpDU5wk4MjE8']/parent::*</value>
      <webElementGuid>2ecc0ebc-58b9-4ab6-b093-7686a01bfe81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://t.me/joinchat/nqPoWpDU5wk4MjE8')]</value>
      <webElementGuid>12bf711c-61e9-4079-9958-03ad82a4f9b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/p/a</value>
      <webElementGuid>2dfaf16b-17e4-4213-a649-3de6f6d3687e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://t.me/joinchat/nqPoWpDU5wk4MjE8' and (text() = 'https://t.me/joinchat/nqPoWpDU5wk4MjE8' or . = 'https://t.me/joinchat/nqPoWpDU5wk4MjE8')]</value>
      <webElementGuid>1b1a9394-1ff5-4888-89f2-04a419a599a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
