<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_pin 4</name>
   <tag></tag>
   <elementGuidId>06943256-b781-4cb3-a1a8-b0d501e2ea98</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#05155d04-8d40-4af3-af76-6cf53153d521-3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='password' and @data-id='3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5f21c13a-2f44-4e20-80bf-76d46a25b8bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>05155d04-8d40-4af3-af76-6cf53153d521-3</value>
      <webElementGuid>92bab518-19a9-40a8-8d56-7ec5b86d4a0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>8b8699bb-a819-474c-a27b-c0c137750017</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>bee10f59-bf22-4e1c-b3a4-f01357f3a8d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9a5d82f1-40a3-4959-ab89-6ccb7d718769</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>83b21b79-e741-4a88-877c-3b16fc9ab753</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>b3f4adc7-6306-4988-a496-d2f2ded8f0e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>chrome-off</value>
      <webElementGuid>b43facbd-7bc8-4dc4-9e77-b449ac82b438</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-valid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9c97dba1-ba6a-4c0b-8df6-84d9c0f4cdf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>/^\d+$/</value>
      <webElementGuid>7352abdd-ea67-4c7c-bc81-87c55bb67d78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;05155d04-8d40-4af3-af76-6cf53153d521-3&quot;)</value>
      <webElementGuid>791521aa-91e8-4443-9ac7-267563f212be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='05155d04-8d40-4af3-af76-6cf53153d521-3']</value>
      <webElementGuid>d9293b5a-486e-4d76-b6f9-1485ae074a3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/div[3]/div/div/div[4]/div/input[4]</value>
      <webElementGuid>61ddaf8e-9299-456f-9efa-b0bbbc184b8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[4]</value>
      <webElementGuid>cdb72d71-5e57-48e0-9b7e-50976dd4ca6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '05155d04-8d40-4af3-af76-6cf53153d521-3' and @type = 'password']</value>
      <webElementGuid>59633962-dc6c-4db1-b714-2b65ee72d184</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
