<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_pin 2</name>
   <tag></tag>
   <elementGuidId>d005a33b-d46d-4ee6-95b9-ff113170827d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#05155d04-8d40-4af3-af76-6cf53153d521-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='password' and @data-id='1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9db72200-48ad-4af4-8d48-2b4538a10b0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>05155d04-8d40-4af3-af76-6cf53153d521-1</value>
      <webElementGuid>73f5c83c-d4d9-406c-9481-a54ab649006b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>027a7402-b95b-495e-985d-e05ab814764c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>fbeb0dc9-1380-44fa-bd57-f6b86f161a03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>38299794-1d81-423d-8894-5c261db26eef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>08e3fad6-1bf9-4341-b3e8-519fd3adc7ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>a3897bf1-30dc-455b-ac14-811f020e06e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>chrome-off</value>
      <webElementGuid>ff796af8-e8e2-41b5-a493-fa1444959435</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-valid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9fe695e2-7e1a-4217-bf34-2b6aee462dc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>/^\d+$/</value>
      <webElementGuid>3a353b9a-0980-422f-b52e-e1da68e675d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;05155d04-8d40-4af3-af76-6cf53153d521-1&quot;)</value>
      <webElementGuid>56ad246e-a8ca-4f52-bc58-9b5356a682e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='05155d04-8d40-4af3-af76-6cf53153d521-1']</value>
      <webElementGuid>ae142c02-5bd4-431b-abe6-0f0929866009</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/div[3]/div/div/div[4]/div/input[2]</value>
      <webElementGuid>25a4d1ce-ac35-4c0a-a7e0-42447667b51a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>880f9a27-18c0-4903-931b-643cdaf545c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '05155d04-8d40-4af3-af76-6cf53153d521-1' and @type = 'password']</value>
      <webElementGuid>d5027e1c-0a73-4aba-ac5f-71b82e965e28</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
